repos:
    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: fmt
          - id: cargo-check
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.6.0" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
            types_or:
                [
                    javascript,
                    ts,
                    tsx,
                    html,
                    json,
                    css,
                    scss,
                    markdown,
                    rst,
                    yaml,
                ]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: mixed-line-ending
            args: ["--fix=lf"]
            types: [text]
          - id: trailing-whitespace
          - id: check-toml
          - id: check-yaml
          - id: check-json
          - id: check-merge-conflict
