[package]
name = "stfmt"
version = "0.1.0"
edition = "2021"
authors = ["John te Bokkel <tanj.tanj@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "^2.0"
pest_derive = "^2.0"
